//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public long OrderItemId { get; set; }
        public long OrderId { get; set; }
        public string ItemName { get; set; }
        public int ItemQty { get; set; }
        public double ItemPrice { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
